# Book Recommendation System

<img src="https://storage.evrimagaci.org/old/content_media/2a10f8a32f8598e61a47f659606911aa.jpg">

<a href="https://thecleverprogrammer.com/2023/10/30/book-recommendation-system-with-python/">Dataya Buradan Erişebilirsiniz</a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("books_data.csv")

### EDA

In [3]:
df

bookID                                              title  \
0           1  Harry Potter and the Half-Blood Prince (Harry ...   
1           2  Harry Potter and the Order of the Phoenix (Har...   
2           4  Harry Potter and the Chamber of Secrets (Harry...   
3           5  Harry Potter and the Prisoner of Azkaban (Harr...   
4           8  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   
...       ...                                                ...   
11122   45631   Expelled from Eden: A William T. Vollmann Reader   
11123   45633                        You Bright and Risen Angels   
11124   45634                    The Ice-Shirt (Seven Dreams #1)   
11125   45639                                        Poor People   
11126   45641                        Las aventuras de Tom Sawyer   

                                                 authors average_rating  
0                             J.K. Rowling/Mary GrandPré           4.57  
1                             J.K. Rowling/Mary GrandPré           4.49  
2                                           J.K. Rowling           4.42  
3                             J.K. Rowling/Mary GrandPré           4.56  
4                             J.K. Rowling/Mary GrandPré           4.78  
...                                                  ...            ...  
11122  William T. Vollmann/Larry McCaffery/Michael He...           4.06  
11123                                William T. Vollmann           4.08  
11124                                William T. Vollmann           3.96  
11125                                William T. Vollmann           3.72  
11126                                         Mark Twain           3.91  

[11127 rows x 4 columns]

In [4]:
df["average_rating"].value_counts()

average_rating
4.00                  219
3.96                  195
4.02                  178
3.94                  176
4.07                  172
                     ... 
2.99                    1
3.03                    1
3.10                    1
 Jr./Sam B. Warner      1
2.33                    1
Name: count, Length: 213, dtype: int64

In [5]:
df.shape

(11127, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   bookID          11127 non-null  int64 
 1   title           11127 non-null  object
 2   authors         11127 non-null  object
 3   average_rating  11127 non-null  object
dtypes: int64(1), object(3)
memory usage: 347.8+ KB


In [7]:
df.title.value_counts()

title
The Brothers Karamazov                                  9
The Iliad                                               9
'Salem's Lot                                            8
The Odyssey                                             8
Gulliver's Travels                                      8
                                                       ..
The Noonday Demon: An Atlas of Depression               1
The Noonday Demon: An Anatomy of Depression             1
My Secret: A PostSecret Book                            1
The Secret Lives of Men and Women: A PostSecret Book    1
Las aventuras de Tom Sawyer                             1
Name: count, Length: 10352, dtype: int64

In [8]:
df.bookID.nunique()

11127

In [9]:
print(df['average_rating'].unique())

['4.57' '4.49' '4.42' '4.56' '4.78' '3.74' '4.73' '4.38' '4.22' '4.21'
 '3.44' '3.87' '4.07' '3.90' '3.83' '3.86' '3.91' '3.93' '4.59' '4.50'
 '4.36' '4.53' '3.84' '3.72' '4.00' '3.88' '4.33' '3.45' '3.76' '3.60'
 '4.06' '4.17' '3.55' '3.98' '4.13' '3.95' '4.24' '4.34' '3.92' '4.23'
 '3.75' '3.94' '3.77' '4.46' '3.68' '3.99' '3.25' '3.89' '3.82' '3.78'
 '4.01' '4.35' '4.28' '3.34' '3.67' '3.48' '3.50' '3.62' '4.27' '3.39'
 '4.12' '4.08' '4.05' '3.85' '2.99' '4.19' '3.71' '4.20' '3.65' '3.40'
 '4.11' '3.42' '4.02' '3.69' '4.10' '3.66' '4.61' '4.04' '3.97' '4.14'
 '3.57' '3.43' '3.22' '3.64' '3.96' '3.80' '3.81' '3.79' '3.23' '4.15'
 '4.39' '4.03' '3.73' '3.51' '3.63' '3.09' '3.59' '4.29' '0.00' '4.25'
 '4.26' '3.61' '4.16' '4.55' '4.52' '3.41' '4.70' '4.18' '3.58' '4.51'
 '3.15' '3.31' '4.09' '3.49' '3.56' '4.47' '4.44' '3.70' '4.32' '4.40'
 '4.31' '4.43' '2.80' '3.46' '2.83' '4.62' '2.67' '4.45' '4.30' '5.00'
 '3.10' '3.08' '3.27' '3.33' '3.00' '4.67' '4.63' '3.52' '3.36' '3.54'
 '3.17

### Feature Engineering

In [10]:
kalkacak = [
    " Jr./Sam B. Warner",
    " one of the founding members of this Tolkien website)/Verlyn Flieger/Turgon (=David E. Smith)",
    " Rawles",
    " Son & Ferguson"
]

df = df[~df["average_rating"].isin(kalkacak)]

In [11]:
df["average_rating"]=df["average_rating"].astype(float)

C:\Users\erkan\AppData\Local\Temp\ipykernel_32624\1092818609.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["average_rating"]=df["average_rating"].astype(float)


In [12]:
author_rows = []

for index, row in df.iterrows():
    authors = row['authors'].split('/')  # Yazarları ayır
    for author in authors:
        author_rows.append({'bookID': row['bookID'], 'title': row['title'], 'author': author.strip(), 'average_rating': row['average_rating']})

In [13]:
ydf=pd.DataFrame(author_rows)

In [14]:
ydf

bookID                                              title  \
0           1  Harry Potter and the Half-Blood Prince (Harry ...   
1           1  Harry Potter and the Half-Blood Prince (Harry ...   
2           2  Harry Potter and the Order of the Phoenix (Har...   
3           2  Harry Potter and the Order of the Phoenix (Har...   
4           4  Harry Potter and the Chamber of Secrets (Harry...   
...       ...                                                ...   
19232   45631   Expelled from Eden: A William T. Vollmann Reader   
19233   45633                        You Bright and Risen Angels   
19234   45634                    The Ice-Shirt (Seven Dreams #1)   
19235   45639                                        Poor People   
19236   45641                        Las aventuras de Tom Sawyer   

                    author  average_rating  
0             J.K. Rowling            4.57  
1            Mary GrandPré            4.57  
2             J.K. Rowling            4.49  
3            Mary GrandPré            4.49  
4             J.K. Rowling            4.42  
...                    ...             ...  
19232   Michael Hemmingson            4.06  
19233  William T. Vollmann            4.08  
19234  William T. Vollmann            3.96  
19235  William T. Vollmann            3.72  
19236           Mark Twain            3.91  

[19237 rows x 4 columns]

In [15]:
ydf["author"].nunique()

9231

In [17]:
# tf idf ile

In [29]:
sss=ydf

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd


# Yazar ve ortalama puanları birleştirerek yeni bir sütun oluştur
sss['combined'] = sss['author']+ " " + sss['title']+" "+sss["average_rating"].astype(str)

# TF-IDF Vektörizeri ile öznitelik matrisini oluştur
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(sss['combined'])

# Kosinüs benzerliği matrisini hesapla
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

[[1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [34]:
def recommend_books(title, cosine_sim=cosine_sim):
    # Verilen başlığa karşılık gelen indeks
    if title not in sss['title'].values:
        return "Kitap bulunamadı."

    idx = sss.index[sss['title'] == title].tolist()[0]
    
    # Benzerlik puanlarını al
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # En benzer 5 kitabı al
    sim_scores = sim_scores[1:6]  # En benzer 5 kitabı al
    
    # Eğer sim_scores'da yeterli kitap yoksa
    if len(sim_scores) == 0:
        return "Yeterli benzer kitap bulunamadı."

    book_indices = [i[0] for i in sim_scores]
    
    # Kitapların bilgilerini al
    recommendations = sss.iloc[book_indices].copy()
    recommendations['similarity'] = [sim_scores[i][1] for i in range(len(sim_scores))]
    
    # Sonuçları döndür
    return recommendations[['title', 'average_rating', 'similarity']]

In [35]:
print(recommend_books('Las aventuras de Tom Sawyer'))

                                                   title  average_rating  \
11163  The Adventures of Tom Sawyer (Adventures of To...            3.91   
11165  The Adventures of Tom Sawyer (Adventures of To...            3.91   
1563   Huck Finn & Tom Sawyer among the Indians & Oth...            3.85   
1567          Huck Finn and Tom Sawyer Among the Indians            3.57   
1590                     The Autobiography of Mark Twain            4.05   

       similarity  
11163    0.531243  
11165    0.531243  
1563     0.450082  
1567     0.414579  
1590     0.412331  


In [37]:
import pickle

In [40]:
# Klasör oluşturma
import os
os.makedirs("my_model", exist_ok=True)

# Modeli ve veriyi kaydet
with open("my_model/tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

sss.to_csv("my_model/books_data.csv", index=False)  # Veriyi CSV olarak kaydet

Kitap adı yazarı ve ortalama puanını tf/idf vectorizer kullanar bir tavsiye modeli olusturduk ve bunu streamlit uygulaması yapmak için pickle dosyasına kaydettik